@startuml

'actors
actor :User: as user
actor :App: as app #lightgreen
actor :API: as api
actor :DB: as db

'main usecases
usecase (View Transactions) as uc_view_transactions
usecase (View Transaction) as uc_view_transaction
usecase (Add Transaction) as uc_add_transaction
usecase (Edit Transaction) as uc_edit_transaction
usecase (Delete Transaction) as uc_delete_transaction

usecase (Transaction List) as uc_transaction_list #lightgreen
usecase (Transaction View) as uc_transaction_view #lightgreen

'scenario
user --> uc_view_transactions
user --> uc_add_transaction
user --> uc_edit_transaction
user --> uc_delete_transaction

'additional'
uc_view_transactions --> uc_view_transaction : includes

'transaction list'
app --> uc_transaction_list : provides
uc_view_transactions --> uc_transaction_list : uses
uc_add_transaction --> uc_transaction_list : uses
uc_edit_transaction --> uc_transaction_list : uses
uc_delete_transaction --> uc_transaction_list : uses

'transaction view'
app --> uc_transaction_view : provides
uc_view_transaction --> uc_transaction_view : uses
uc_add_transaction --> uc_transaction_view : uses
uc_edit_transaction --> uc_transaction_view : uses
uc_delete_transaction --> uc_transaction_view : uses



@enduml
