@startuml
start

:Start app;

:Click menu "Transactions" -> "Create new transaction...";

partition "Fill data fields" {
  :Specify withdrowal account;
  :Specify deposit account;
  :Specify payment amount and currency;
  :Specify blocked amount and currency;
  :Specify actually withdrown amount and currency;

  if (Have transaction description?) then (yes)
    :Specify transaction description;
  else (no)
  endif

  :Specify transaction date;
}

if (Add this transaction?) then (yes)
  :Click "Submit" button;
else (no)
  fork
    :Close "Add Transaction" tab;
  fork again
    :Click "Cancel" button;
  end fork
endif

end
@enduml
